apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapidpro.fullname" . }}-rapidpro-config
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
data:
  MAILROOM_URL: "http://{{ include "rapidpro.fullname" . }}-mailroom:8091"
  CELERY_BROKER_URL: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/{{ .Values.redis.db }}"
  MAILROOM_AUTH_TOKEN: {{ .Values.tokens.mailroomAuthToken | quote }}
  EMAIL_HOST_USER: {{ .Values.email.fromEmail | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.emailPassword | quote }}
  EMAIL_HOST: {{ .Values.email.host | quote }}
  EMAIL_PORT: {{ .Values.email.port | quote }}
  EMAIL_USE_TLS: {{ .Values.email.useTLS | quote }}
  EMAIL_USE_SSL: {{ .Values.email.useSSL | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.email.fromEmail | quote }}
  FLOW_FROM_EMAIL: {{ .Values.email.fromEmail | quote }}
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  POSTGRES_HOST: "127.0.0.1"
  POSTGRES_PORT: {{ .Values.database.port | quote }}
  DJANGO_DEBUG: "false"
  VIEWER_PERMISSIONS: |
    campaigns.campaign_list
    campaigns.campaign_menu
    campaigns.campaign_read 
    campaigns.campaignevent_list
    campaigns.campaignevent_read
    channels.channel_list
    channels.channel_read
    channels.channelevent_list
    contacts.contact_export
    contacts.contact_list
    contacts.contact_menu
    contacts.contact_read
    contacts.contact_chat
    contacts.contactfield_list
    contacts.contactfield_read
    contacts.contactgroup_list
    contacts.contactgroup_menu
    contacts.contactgroup_read
    contacts.contactimport_read
    flows.flow_assets
    flows.flow_editor
    flows.flow_export
    flows.flow_list
    flows.flow_menu
    flows.flow_results
    flows.flowrun_list
    flows.flowstart_list
    globals.global_list
    globals.global_read
    ivr.call_list
    locations.adminboundary_alias
    locations.adminboundary_boundaries
    locations.adminboundary_geometry
    locations.adminboundary_list
    msgs.broadcast_list
    msgs.broadcast_scheduled
    msgs.label_list
    msgs.label_read
    msgs.msg_export
    msgs.msg_list
    msgs.msg_menu
    msgs.optin_list
    notifications.notification_list
    orgs.org_download
    orgs.org_export
    orgs.org_menu
    orgs.org_read
    orgs.org_workspace
    users.user_list
    templates.template_list
    templates.template_read
    tickets.ticket_export
    tickets.ticket_list
    tickets.ticket_menu
    tickets.topic_list
    triggers.trigger_list
    triggers.trigger_menu