apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rapidpro.fullname" . }}-rapidpro
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.rapidpro.enabled }}
  replicas: {{ .Values.replicaCount.rapidpro }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rapidpro.selectorLabels" . | nindent 6 }}
      component: rapidpro
  template:
    metadata:
      labels:
        {{- include "rapidpro.selectorLabels" . | nindent 8 }}
        component: rapidpro
    spec:
      containers:
        - name: rapidpro
          image: "{{ .Values.images.rapidpro.repository }}:{{ .Values.images.rapidpro.tag }}"
          imagePullPolicy: {{ .Values.images.rapidpro.pullPolicy }}
          # command:
          #   - tail
          #   - -f
          #   - /dev/null
          args:
            - webapp
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "rapidpro.fullname" . }}-config
            - configMapRef:
                name: {{ include "rapidpro.fullname" . }}-rapidpro-config
            - secretRef:
                name: {{ include "rapidpro.fullname" . }}-secrets
          env:
            - name: DYNAMO_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rapidpro.fullname" . }}-config
                  key: DYNAMO_ENDPOINT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rapidpro.fullname" . }}-secrets
                  key: DB_PASSWORD
            - name: ELASTIC_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "rapidpro.fullname" . }}-config
                  key: ELASTIC_URL
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }} 
          resources:
            {{- toYaml .Values.resources.rapidpro | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /msg
              port: 8000
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /msg
              port: 8000
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 12
          
          volumeMounts:
            # Este bloque agarra el "disco" de arriba y lo mete en una carpeta dentro del contenedor
            - name: gcs-key-volume
              mountPath: /var/secrets/google
              readOnly: true
        
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.cloudsql.instanceConnectionName }}=tcp:5432"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      volumes:
        # Este bloque le dice al Pod: "Ve a buscar el Secret de Helm y prepáralo como un disco"
        - name: gcs-key-volume
          secret:
            secretName: rapidpro-gcs-credentials
