apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapidpro.fullname" . }}-rapidpro
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "rapidpro.selectorLabels" . | nindent 4 }}
    component: rapidpro
