apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rapidpro.fullname" . }}-dynamodb
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
    component: dynamodb
spec:
  serviceName: {{ include "rapidpro.fullname" . }}-dynamodb
  replicas: 1
  selector:
    matchLabels:
      {{- include "rapidpro.selectorLabels" . | nindent 6 }}
      component: dynamodb
  template:
    metadata:
      labels:
        {{- include "rapidpro.selectorLabels" . | nindent 8 }}
        component: dynamodb
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local
          command: ["java", "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: dynamodb-data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                [
                  "sh", "-c",
                  "curl -s -X POST http://localhost:8000 -H 'X-Amz-Target: DynamoDB_20120810.ListTables' -H 'Content-Type: application/x-amz-json-1.0' -d '{}' >/dev/null || exit 1"
                ]
            initialDelaySeconds: 90
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: dynamodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 5Gi