apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapidpro.fullname" . }}-mailroom-config
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
data:
  MAILROOM_ADDRESS: "0.0.0.0"
  # MAILROOM_DOMAIN: "{{ include "rapidpro.fullname" . }}-courier:8080"
  # MAILROOM_ATTACHMENT_DOMAIN: "{{ include "rapidpro.fullname" . }}-courier:8080"
  MAILROOM_DOMAIN: "rapidpro.nncd.mx"
  MAILROOM_ATTACHMENT_DOMAIN: "rapidpro.nncd.mx"
  MAILROOM_DISALLOWED_NETWORKS: "6.6.6.6"
  MAILROOM_LOG_LEVEL: "info"
  MAILROOM_AWS_REGION: {{ .Values.aws.region | quote }}
  AWS_EC2_METADATA_DISABLED: "true"