apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapidpro.fullname" . }}-mailroom
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    {{- include "rapidpro.selectorLabels" . | nindent 4 }}
    component: mailroom
