{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rapidpro.fullname" . }}-ingress
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:

          # =========================
          # RapidPro Web
          # =========================
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rapidpro.fullname" . }}-rapidpro
                port:
                  number: 8000

          # =========================
          # Mailroom
          # =========================
          - path: /mr/
            pathType: Prefix
            backend:
              service:
                name: {{ include "rapidpro.fullname" . }}-mailroom
                port:
                  number: 8090

          # =========================
          # Courier
          # =========================
          - path: /c/
            pathType: Prefix
            backend:
              service:
                name: {{ include "rapidpro.fullname" . }}-courier
                port:
                  number: 8080

{{- end }}