# templates/gcs-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rapidpro-gcs-credentials
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }} # Usa los helpers de labels de tu chart si existen
type: Opaque
data:
  # .Files.Get lee el archivo local durante el empaquetado/despliegue de Helm y b64enc lo encripta en Base64 (requerido por K8s)
  gcs-sa.json: {{ .Files.Get "secrets/gcs-sa.json" | b64enc }}