apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rapidpro.fullname" . }}-secrets
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | required "DJANGO_SECRET_KEY required" }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | required "DB_PASSWORD required" }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | required "ENCRYPTION_KEY required" }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.emailPassword | default "" }}
  MAILROOM_AUTH_TOKEN: {{ .Values.tokens.mailroomAuthToken | quote }}
  COURIER_AUTH_TOKEN: {{ .Values.tokens.courierAuthToken | quote }}
  AWS_SECRET_ACCESS_KEY: "tembatemba"
