apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapidpro.fullname" . }}-courier
  labels:
    {{- include "rapidpro.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "rapidpro.fullname" . }}-courier-backendconfig"}'
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: internal
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: external
  selector:
    {{- include "rapidpro.selectorLabels" . | nindent 4 }}
    component: courier
